### ISSUE TITLE
Подстрочный перевод статьи "Using functions as building blocks" 

### ISSUE THREAD

**Issue by sergeiwork** [max-arshinov/fsharpforfunandprofit.ru#21]
Ссылка на [оригинал](https://github.com/swlaschin/fsharpforfunandprofit.com/blob/master/content/posts/conciseness-functions-as-building-blocks/index.md)
Предполагаемое название на русском: "Использование функций в качестве строительных блоков"

**Comment by markshevchenko** [comment]
Перевод завершён, прорецензирован двумя редакторами и влит в мастер.
