### ISSUE TITLE
Список статей к переводу

### ISSUE THREAD

**Issue by kant2002** [max-arshinov/fsharpforfunandprofit.ru#3]
Ниже список статей которые надо перевести.

https://docs.google.com/spreadsheets/d/1Z82DAou_UDwn1GR5G8G2yS6s92Lojexv-ZsR63N6oPs/edit?usp=sharing

Если, хотите выбрать статью, то напишите сюда, чтобы вас добавили в список.

<details>
 <summary>Список статей сформирован кодом</summary>

```bash
i=1
for f in $(find content -name '*.md' -type f) 
do 
    title=$(grep "title:" $f | awk -F : '{print $2'})
    echo "| $i | [$title](https://github.com/swlaschin/fsharpforfunandprofit.com/blob/master/$f) | $f |"
    i=$((i+1))
done
```
</details>

**Comment by sergeiwork** [comment]
Список выше далеко не полный. `find content -name '*.md' -type f` выдает больше результатов
[Вот что у меня получилось](https://gist.github.com/sergeiwork/49ea2cd9c0e9e1b243fc12bf6c159bc7)

**Comment by SeminDM** [comment]
список постов
https://github.com/swlaschin/fsharpforfunandprofit.com/tree/master/content/posts

**Comment by max-arshinov** [comment]
Нужно еще отсортировать по приоритетам, что в первую очередь, что во вторую. Можно в гугл док добавить и там проголосовать. После этого перенести полный список сюда

**Comment by SeminDM** [comment]
https://docs.google.com/spreadsheets/d/1Z82DAou_UDwn1GR5G8G2yS6s92Lojexv-ZsR63N6oPs/edit?usp=sharing

**Comment by SeminDM** [comment]
А у каких разделов более высокий приоритет?

**Comment by markshevchenko** [comment]
Перенёс список статей в [How to contribute](https://github.com/max-arshinov/fsharpforfunandprofit.ru/blob/master/how-to-contribute/_index.md).
